import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'en',
        'es',
        'fr',
        'am',
        'zh_Hant',
        'zh_Hans',
        'ar',
        'ru',
        'ne',
        'ja',
        'vi'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? esText = '',
    String? frText = '',
    String? amText = '',
    String? zh_HantText = '',
    String? zh_HansText = '',
    String? arText = '',
    String? ruText = '',
    String? neText = '',
    String? jaText = '',
    String? viText = '',
  }) =>
      [
        enText,
        esText,
        frText,
        amText,
        zh_HantText,
        zh_HansText,
        arText,
        ruText,
        neText,
        jaText,
        viText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // Auth1
  {
    'ptgdud97': {
      'en': 'Sign In',
      'am': 'ስግን እን',
      'ar': 'تسجيل الدخول',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'ja': 'サインイン',
      'ne': 'साइन इन गर्नुहोस्',
      'ru': 'Войти',
      'vi': 'Đăng nhập',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    'aea8i1hg': {
      'en': 'Sign Up',
      'am': 'ተመዝገቢ',
      'ar': 'اشتراك',
      'es': 'Inscribirse',
      'fr': 'S\'inscrire',
      'ja': 'サインアップ',
      'ne': 'साइन अप',
      'ru': 'Зарегистрироваться',
      'vi': 'Đăng ký',
      'zh_Hans': '报名',
      'zh_Hant': '報名',
    },
    'folmk9vz': {
      'en': 'Let\'s get started by filling out the form below.',
      'am': 'ከዚህ በታች ያለውን ቅጽ በመሙላት እንጀምር።',
      'ar': 'لنبدأ بملء النموذج أدناه.',
      'es': 'Comencemos completando el formulario a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'ja': '以下のフォームに記入して始めましょう。',
      'ne': 'तलको फारम भरेर सुरु गरौं।',
      'ru': 'Начнем с заполнения формы ниже.',
      'vi': 'Hãy bắt đầu bằng cách điền vào mẫu dưới đây.',
      'zh_Hans': '让我们开始填写下面的表格。',
      'zh_Hant': '讓我們開始填寫下面的表格。',
    },
    'nnq8cv79': {
      'en': 'Email',
      'am': 'ኢሜይል',
      'ar': 'بريد إلكتروني',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'ja': 'Eメール',
      'ne': 'इमेल',
      'ru': 'Электронная почта',
      'vi': 'E-mail',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    'h57igsv8': {
      'en': 'Password',
      'am': 'የይለፍ ቃል',
      'ar': 'كلمة المرور',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'ja': 'パスワード',
      'ne': 'पासवर्ड',
      'ru': 'Пароль',
      'vi': 'Mật khẩu',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'xv7rwdbg': {
      'en': 'Sign In',
      'am': 'ስግን እን',
      'ar': 'تسجيل الدخول',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'ja': 'サインイン',
      'ne': 'साइन इन गर्नुहोस्',
      'ru': 'Войти',
      'vi': 'Đăng nhập',
      'zh_Hans': '登入',
      'zh_Hant': '登入',
    },
    'k9dn9hpx': {
      'en': 'Forgot Password',
      'am': 'መክፈቻ ቁልፉን ረሳኽው',
      'ar': 'هل نسيت كلمة السر',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'ja': 'パスワードをお忘れですか',
      'ne': 'पासवर्ड भुल्नु भयो',
      'ru': 'Забыли пароль',
      'vi': 'Quên mật khẩu',
      'zh_Hans': '忘记密码',
      'zh_Hant': '忘記密碼',
    },
    'gxt8fdw5': {
      'en': 'Or sign up with',
      'am': 'ወይም በ ይመዝገቡ',
      'ar': 'أو قم بالتسجيل مع',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'ja': 'または、次のようにサインアップしてください',
      'ne': 'वा साइन अप गर्नुहोस्',
      'ru': 'Или зарегистрируйтесь через',
      'vi': 'Hoặc đăng ký với',
      'zh_Hans': '或者注册',
      'zh_Hant': '或註冊',
    },
    '9ybv0el6': {
      'en': 'Continue with Google',
      'am': 'በGoogle ይቀጥሉ',
      'ar': 'تواصل مع جوجل',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'ja': 'Google を続ける',
      'ne': 'Google को साथ जारी राख्नुहोस्',
      'ru': 'Продолжить с Google',
      'vi': 'Tiếp tục với Google',
      'zh_Hans': '继续使用谷歌',
      'zh_Hant': '繼續使用谷歌',
    },
    'il9qxs72': {
      'en': 'Email',
      'am': 'ኢሜይል',
      'ar': 'بريد إلكتروني',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'ja': 'Eメール',
      'ne': 'इमेल',
      'ru': 'Электронная почта',
      'vi': 'E-mail',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    'tnjety0i': {
      'en': 'Password',
      'am': 'የይለፍ ቃል',
      'ar': 'كلمة المرور',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'ja': 'パスワード',
      'ne': 'पासवर्ड',
      'ru': 'Пароль',
      'vi': 'Mật khẩu',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'fwgn1fdr': {
      'en': 'Confirm Password',
      'am': 'የይለፍ ቃል አረጋግጥ',
      'ar': 'تأكيد كلمة المرور',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'ja': 'パスワードを認証する',
      'ne': 'पासवर्ड सुनिश्चित गर्नुहोस',
      'ru': 'Подтвердите пароль',
      'vi': 'Xác nhận mật khẩu',
      'zh_Hans': '确认密码',
      'zh_Hant': '確認密碼',
    },
    '9hpxvf65': {
      'en': 'Create Account',
      'am': 'መለያ ይፍጠሩ',
      'ar': 'إنشاء حساب',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'ja': 'アカウントを作成する',
      'ne': 'खाता सिर्जना गर्नुहोस्',
      'ru': 'Зарегистрироваться',
      'vi': 'Tạo tài khoản',
      'zh_Hans': '创建账户',
      'zh_Hant': '建立帳戶',
    },
    'rzickb4f': {
      'en': 'Or sign up with',
      'am': 'ወይም በ ይመዝገቡ',
      'ar': 'أو قم بالتسجيل مع',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'ja': 'または、次のようにサインアップしてください',
      'ne': 'वा साइन अप गर्नुहोस्',
      'ru': 'Или зарегистрируйтесь через',
      'vi': 'Hoặc đăng ký với',
      'zh_Hans': '或者注册',
      'zh_Hant': '或註冊',
    },
    'sao90i2k': {
      'en': 'Continue with Google',
      'am': 'በGoogle ይቀጥሉ',
      'ar': 'تواصل مع جوجل',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'ja': 'Google を続ける',
      'ne': 'Google को साथ जारी राख्नुहोस्',
      'ru': 'Продолжить с Google',
      'vi': 'Tiếp tục với Google',
      'zh_Hans': '继续使用谷歌',
      'zh_Hant': '繼續使用谷歌',
    },
    '57w7450i': {
      'en': 'Home',
      'am': 'ቤት',
      'ar': 'بيت',
      'es': 'Hogar',
      'fr': 'Maison',
      'ja': '家',
      'ne': 'घर',
      'ru': 'Дом',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // profileView
  {
    '09y6mxfs': {
      'en': 'Your Account',
      'am': 'መለያህ',
      'ar': 'الحساب الخاص بك',
      'es': 'Su cuenta',
      'fr': 'Votre compte',
      'ja': 'あなたのアカウント',
      'ne': 'तपाईंको खाता',
      'ru': 'Ваш счет',
      'vi': 'Tài khoản của bạn',
      'zh_Hans': '你的帐户',
      'zh_Hant': '你的帳戶',
    },
    'xpa8k14a': {
      'en': 'Edit Profile',
      'am': 'መገለጫ አርትዕ',
      'ar': 'تعديل الملف الشخصي',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'ja': 'プロファイル編集',
      'ne': 'प्रोफाइल सम्पादन गर',
      'ru': 'Редактировать профиль',
      'vi': 'Chỉnh sửa hồ sơ',
      'zh_Hans': '编辑个人资料',
      'zh_Hant': '編輯個人資料',
    },
    '73uam1cl': {
      'en': 'Change Password',
      'am': 'የሚስጥር ቁልፍ ይቀይሩ',
      'ar': 'تغيير كلمة المرور',
      'es': 'Cambiar la contraseña',
      'fr': 'Changer le mot de passe',
      'ja': 'パスワードを変更する',
      'ne': 'पासवर्ड परिवर्तन गर्नुहोस्',
      'ru': 'Изменить пароль',
      'vi': 'Đổi mật khẩu',
      'zh_Hans': '更改密码',
      'zh_Hant': '更改密碼',
    },
    'jrqxqs8g': {
      'en': 'App Settings',
      'am': 'የመተግበሪያ ቅንብሮች',
      'ar': 'إعدادات التطبيقات',
      'es': 'Ajustes de Aplicacion',
      'fr': 'Paramètres de l\'application',
      'ja': 'アプリの設定',
      'ne': 'एप सेटिङहरू',
      'ru': 'Настройки приложения',
      'vi': 'Cài đặt ứng dụng',
      'zh_Hans': '应用程序设置',
      'zh_Hant': '應用程式設定',
    },
    'rikuvc5b': {
      'en': 'Support',
      'am': 'ድጋፍ',
      'ar': 'يدعم',
      'es': 'Apoyo',
      'fr': 'Soutien',
      'ja': 'サポート',
      'ne': 'समर्थन',
      'ru': 'Поддерживать',
      'vi': 'Ủng hộ',
      'zh_Hans': '支持',
      'zh_Hant': '支援',
    },
    'owq2cgzj': {
      'en': 'Terms of Service',
      'am': 'የአገልግሎት ውል',
      'ar': 'شروط الخدمة',
      'es': 'Términos de servicio',
      'fr': 'Conditions d\'utilisation',
      'ja': '利用規約',
      'ne': 'सेवाका सर्तहरु',
      'ru': 'Условия использования',
      'vi': 'Điều khoản dịch vụ',
      'zh_Hans': '服务条款',
      'zh_Hant': '服務條款',
    },
    'dt9n4wmt': {
      'en': 'Light Mode',
      'am': 'የብርሃን ሁነታ',
      'ar': 'وضع الضوء',
      'es': 'Modo de luz',
      'fr': 'Mode lumière',
      'ja': 'ライトモード',
      'ne': 'लाइट मोड',
      'ru': 'Светлый режим',
      'vi': 'Chế độ sáng',
      'zh_Hans': '灯光模式',
      'zh_Hant': '燈光模式',
    },
    '6pysrz82': {
      'en': 'Dark Mode',
      'am': 'ጨለማ ሁነታ',
      'ar': 'الوضع المظلم',
      'es': 'Modo oscuro',
      'fr': 'Mode sombre',
      'ja': 'ダークモード',
      'ne': 'गाढा मोड',
      'ru': 'Темный режим',
      'vi': 'Chế độ tối',
      'zh_Hans': '深色模式',
      'zh_Hant': '深色模式',
    },
    'nig2nxw7': {
      'en': 'Log Out',
      'am': 'ውጣ',
      'ar': 'تسجيل خروج',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'ja': 'ログアウト',
      'ne': 'बाहिर निस्कनु',
      'ru': 'Выйти',
      'vi': 'Đăng xuất',
      'zh_Hans': '登出',
      'zh_Hant': '登出',
    },
    '26hts0th': {
      'en': 'Profile',
      'am': 'መገለጫ',
      'ar': 'حساب تعريفي',
      'es': 'Perfil',
      'fr': 'Profil',
      'ja': 'プロフィール',
      'ne': 'प्रोफाइल',
      'ru': 'Профиль',
      'vi': 'Hồ sơ',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
    'ju8id7lp': {
      'en': 'Profile',
      'am': 'መገለጫ',
      'ar': 'حساب تعريفي',
      'es': 'Perfil',
      'fr': 'Profil',
      'ja': 'プロフィール',
      'ne': 'प्रोफाइल',
      'ru': 'Профиль',
      'vi': 'Hồ sơ',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
  },
  // homePage
  {
    '0qeg43sx': {
      'en': 'Hey',
      'am': 'ሄይ',
      'ar': 'يا',
      'es': 'Ey',
      'fr': 'Hé',
      'ja': 'おい',
      'ne': 'हे',
      'ru': 'Привет',
      'vi': 'Chào',
      'zh_Hans': '嘿',
      'zh_Hant': '嘿',
    },
    'u4m3115x': {
      'en': ',',
      'am': ',',
      'ar': ',',
      'es': ',',
      'fr': ',',
      'ja': '、',
      'ne': ',',
      'ru': ',',
      'vi': ',',
      'zh_Hans': ',',
      'zh_Hant': ',',
    },
    'muajapnp': {
      'en': 'Lets Jump In.',
      'am': 'እንግባ።',
      'ar': 'يتيح القفز في.',
      'es': 'Saltemos.',
      'fr': 'Allons-y.',
      'ja': '飛び込みましょう。',
      'ne': 'हाम फाल्न दिनुहोस्।',
      'ru': 'Давайте прыгнем.',
      'vi': 'Hãy nhảy vào.',
      'zh_Hans': '让我们跳进去吧。',
      'zh_Hant': '讓我們跳進去吧。',
    },
    'g80flidl': {
      'en': 'Choose Your Path.',
      'am': 'መንገድዎን ይምረጡ።',
      'ar': 'اختيار المسار الخاص.',
      'es': 'Elige tu camino.',
      'fr': 'Choisissez votre chemin.',
      'ja': '自分の道を選択してください。',
      'ne': 'आफ्नो बाटो छान्नुहोस्।',
      'ru': 'Выберите свой путь.',
      'vi': 'Chọn con đường của bạn.',
      'zh_Hans': '选择你的道路。',
      'zh_Hant': '選擇你的道路。',
    },
    '3cku64h0': {
      'en': 'Explore the Digital World',
      'am': 'ዲጂታል አለምን ያስሱ',
      'ar': 'اكتشف العالم الرقمي',
      'es': 'Explora el mundo digital',
      'fr': 'Explorez le monde numérique',
      'ja': 'デジタル世界を探索する',
      'ne': 'डिजिटल संसार अन्वेषण गर्नुहोस्',
      'ru': 'Исследуйте цифровой мир',
      'vi': 'Khám phá thế giới kỹ thuật số',
      'zh_Hans': '探索数字世界',
      'zh_Hant': '探索數位世界',
    },
    '3nlrqlxc': {
      'en': 'Training Zone',
      'am': 'የስልጠና ዞን',
      'ar': 'منطقة التدريب',
      'es': 'Zona de entrenamiento',
      'fr': 'Zone d\'entraînement',
      'ja': 'トレーニングゾーン',
      'ne': 'प्रशिक्षण क्षेत्र',
      'ru': 'Тренировочная зона',
      'vi': 'Khu tập luyện',
      'zh_Hans': '训练区',
      'zh_Hant': '訓練區',
    },
    'eusrqrvm': {
      'en': 'Pick up some quick, impactful skills.',
      'am': 'አንዳንድ ፈጣን እና ተጽዕኖ ችሎታዎችን ይምረጡ።',
      'ar': 'احصل على بعض المهارات السريعة والمؤثرة.',
      'es': 'Adquiera algunas habilidades rápidas e impactantes.',
      'fr': 'Acquérez des compétences rapides et percutantes.',
      'ja': '素早く効果的なスキルを身につけましょう。',
      'ne': 'केही छिटो, प्रभावकारी सीपहरू उठाउनुहोस्।',
      'ru': 'Приобретите несколько быстрых и эффективных навыков.',
      'vi': 'Học một số kỹ năng nhanh chóng và có tác động.',
      'zh_Hans': '掌握一些快速、有影响力的技能。',
      'zh_Hant': '掌握一些快速、有影響力的技能。',
    },
    '249w33am': {
      'en': 'Home',
      'am': 'ቤት',
      'ar': 'بيت',
      'es': 'Hogar',
      'fr': 'Maison',
      'ja': '家',
      'ne': 'घर',
      'ru': 'Дом',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // changePass
  {
    'vpzdtucc': {
      'en': 'Back',
      'am': 'ተመለስ',
      'ar': 'خلف',
      'es': 'Atrás',
      'fr': 'Dos',
      'ja': '戻る',
      'ne': 'पछाडि',
      'ru': 'Назад',
      'vi': 'Mặt sau',
      'zh_Hans': '后退',
      'zh_Hant': '後退',
    },
    'hda23d0h': {
      'en': 'Forgot Password',
      'am': 'መክፈቻ ቁልፉን ረሳኽው',
      'ar': 'هل نسيت كلمة السر',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'ja': 'パスワードをお忘れですか',
      'ne': 'पासवर्ड भुल्नु भयो',
      'ru': 'Забыли пароль',
      'vi': 'Quên mật khẩu',
      'zh_Hans': '忘记密码',
      'zh_Hant': '忘記密碼',
    },
    'ndwgikmo': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account below.',
      'am':
          'የይለፍ ቃልዎን እንደገና የሚያስጀምሩበት አገናኝ ያለው ኢሜል እንልክልዎታለን፣ እባክዎ ከመለያዎ ጋር የተያያዘውን ኢሜል ያስገቡ።',
      'ar':
          'سنرسل إليك بريدًا إلكترونيًا يحتوي على رابط لإعادة تعيين كلمة المرور الخاصة بك، يرجى إدخال البريد الإلكتروني المرتبط بحسابك أدناه.',
      'es':
          'Le enviaremos un correo electrónico con un enlace para restablecer su contraseña; ingrese el correo electrónico asociado con su cuenta a continuación.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe, veuillez saisir l\'e-mail associé à votre compte ci-dessous.',
      'ja':
          'パスワードをリセットするためのリンクが記載された電子メールを送信します。以下にアカウントに関連付けられた電子メールを入力してください。',
      'ne':
          'हामी तपाइँलाई तपाइँको पासवर्ड रिसेट गर्नको लागि लिङ्क सहितको इमेल पठाउने छौँ, कृपया तल तपाइँको खातासँग सम्बन्धित इमेल प्रविष्ट गर्नुहोस्।',
      'ru':
          'Мы отправим вам электронное письмо со ссылкой для сброса пароля. Введите адрес электронной почты, связанный с вашей учетной записью, ниже.',
      'vi':
          'Chúng tôi sẽ gửi cho bạn một email có liên kết để đặt lại mật khẩu, vui lòng nhập email được liên kết với tài khoản của bạn bên dưới.',
      'zh_Hans': '我们将向您发送一封电子邮件，其中包含重置密码的链接，请在下面输入与您的帐户关联的电子邮件。',
      'zh_Hant': '我們將向您發送一封電子郵件，其中包含重置密碼的鏈接，請在下面輸入與您的帳戶關聯的電子郵件。',
    },
    'rca44dkj': {
      'en': 'Your email address...',
      'am': 'የኢሜል አድራሻህ...',
      'ar': 'عنوان بريدك  الإلكتروني...',
      'es': 'Su dirección de correo electrónico...',
      'fr': 'Votre adresse e-mail...',
      'ja': 'あなたのメールアドレス...',
      'ne': 'तपाईँको ई - मेल ठेगाना...',
      'ru': 'Ваш электронный адрес...',
      'vi': 'Địa chỉ email của bạn...',
      'zh_Hans': '您的电子邮件地址...',
      'zh_Hant': '您的電子郵件地址...',
    },
    'f5iihyk7': {
      'en': 'Enter your email...',
      'am': 'የእርስዎን ኢሜይል ያስገቡ...',
      'ar': 'أدخل بريدك الإلكتروني...',
      'es': 'Introduce tu correo electrónico...',
      'fr': 'Entrer votre Email...',
      'ja': 'メールアドレスを入力...',
      'ne': 'आफ्नो इमेल प्रविष्ट गर्नुहोस्...',
      'ru': 'Введите адрес электронной почты...',
      'vi': 'Nhập email của bạn...',
      'zh_Hans': '输入你的电子邮箱...',
      'zh_Hant': '輸入你的電子郵件...',
    },
    '42xrwh8e': {
      'en': 'Send Link',
      'am': 'አገናኝ ላክ',
      'ar': 'أرسل الرابط',
      'es': 'Enviar enlace',
      'fr': 'Envoyer un lien',
      'ja': 'リンクを送る',
      'ne': 'लिङ्क पठाउनुहोस्',
      'ru': 'Отправить ссылку',
      'vi': 'Gửi link',
      'zh_Hans': '发送链接',
      'zh_Hant': '發送連結',
    },
    'iea568x1': {
      'en': 'Back',
      'am': 'ተመለስ',
      'ar': 'خلف',
      'es': 'Atrás',
      'fr': 'Dos',
      'ja': '戻る',
      'ne': 'पछाडि',
      'ru': 'Назад',
      'vi': 'Mặt sau',
      'zh_Hans': '后退',
      'zh_Hant': '後退',
    },
    'jrjkrmhr': {
      'en': 'Home',
      'am': 'ቤት',
      'ar': 'بيت',
      'es': 'Hogar',
      'fr': 'Maison',
      'ja': '家',
      'ne': 'घर',
      'ru': 'Дом',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // longTasksLessons
  {
    '309a1wru': {
      'en': 'Class Details',
      'am': 'የክፍል ዝርዝሮች',
      'ar': 'تفاصيل الفصل',
      'es': 'Detalles de la clase',
      'fr': 'Détails du cours',
      'ja': 'クラス詳細',
      'ne': 'कक्षा विवरण',
      'ru': 'Детали класса',
      'vi': 'Chi tiết lớp học',
      'zh_Hans': '课程详情',
      'zh_Hant': '課程詳情',
    },
    'w50hpbeq': {
      'en': 'Content',
      'am': 'ይዘት',
      'ar': 'محتوى',
      'es': 'Contenido',
      'fr': 'Contenu',
      'ja': 'コンテンツ',
      'ne': 'सामग्री',
      'ru': 'Содержание',
      'vi': 'Nội dung',
      'zh_Hans': '内容',
      'zh_Hant': '內容',
    },
    'yn0lfsfw': {
      'en': 'mins',
      'am': 'ደቂቃ',
      'ar': 'دقيقة',
      'es': 'minutos',
      'fr': 'minutes',
      'ja': '分',
      'ne': 'मिनेट',
      'ru': 'минут',
      'vi': 'phút',
      'zh_Hans': '分钟',
      'zh_Hant': '分分鐘',
    },
    '7tcbeg1d': {
      'en': 'Home',
      'am': 'ቤት',
      'ar': 'بيت',
      'es': 'Hogar',
      'fr': 'Maison',
      'ja': '家',
      'ne': 'घर',
      'ru': 'Дом',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // shortTaskLessons
  {
    'adh0zdpy': {
      'en': 'Home',
      'am': 'ቤት',
      'ar': 'بيت',
      'es': 'Hogar',
      'fr': 'Maison',
      'ja': '家',
      'ne': 'घर',
      'ru': 'Дом',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // MyCourses
  {
    'gap785ic': {
      'en': 'Courses',
      'am': 'ኮርሶች',
      'ar': 'الدورات',
      'es': 'Cursos',
      'fr': 'Cours',
      'ja': 'コース',
      'ne': 'पाठ्यक्रमहरू',
      'ru': 'Курсы',
      'vi': 'Khóa học',
      'zh_Hans': '培训班',
      'zh_Hant': '培訓班',
    },
    '1tmjbj60': {
      'en': 'Courses',
      'am': 'ኮርሶች',
      'ar': 'الدورات',
      'es': 'Cursos',
      'fr': 'Cours',
      'ja': 'コース',
      'ne': 'पाठ्यक्रमहरू',
      'ru': 'Курсы',
      'vi': 'Khóa học',
      'zh_Hans': '培训班',
      'zh_Hant': '培訓班',
    },
  },
  // CourseCategory
  {
    '3pox7q1a': {
      'en': 'Courses',
      'am': 'ኮርሶች',
      'ar': 'الدورات',
      'es': 'Cursos',
      'fr': 'Cours',
      'ja': 'コース',
      'ne': 'पाठ्यक्रमहरू',
      'ru': 'Курсы',
      'vi': 'Khóa học',
      'zh_Hans': '培训班',
      'zh_Hant': '培訓班',
    },
    'md9hhkw7': {
      'en': 'Courses',
      'am': 'ኮርሶች',
      'ar': 'الدورات',
      'es': 'Cursos',
      'fr': 'Cours',
      'ja': 'コース',
      'ne': 'पाठ्यक्रमहरू',
      'ru': 'Курсы',
      'vi': 'Khóa học',
      'zh_Hans': '培训班',
      'zh_Hant': '培訓班',
    },
  },
  // LongTaskIntro
  {
    'qv8fvap0': {
      'en': 'Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // FavoriteCourses
  {
    '483xz628': {
      'en': 'Favorite',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'mmp1how7': {
      'en': 'Courses',
      'am': 'ኮርሶች',
      'ar': 'الدورات',
      'es': 'Cursos',
      'fr': 'Cours',
      'ja': 'コース',
      'ne': 'पाठ्यक्रमहरू',
      'ru': 'Курсы',
      'vi': 'Khóa học',
      'zh_Hans': '培训班',
      'zh_Hant': '培訓班',
    },
    'hxe1qojk': {
      'en': 'Courses',
      'am': 'ኮርሶች',
      'ar': 'الدورات',
      'es': 'Cursos',
      'fr': 'Cours',
      'ja': 'コース',
      'ne': 'पाठ्यक्रमहरू',
      'ru': 'Курсы',
      'vi': 'Khóa học',
      'zh_Hans': '培训班',
      'zh_Hant': '培訓班',
    },
  },
  // ShortContentSection
  {
    '2vkh2sw9': {
      'en': 'Explore Here!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nfihtf7n': {
      'en': 'Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // quizComplete
  {
    'k64qcscm': {
      'en': 'Congrats!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9i388bfn': {
      'en': 'Thanks for taking the quiz. ',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'liehd1s3': {
      'en': '  correct ',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j8ds47sn': {
      'en': 'Get 100% to increase your streak!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fu30dtbf': {
      'en': 'Go Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1zahqgtp': {
      'en': 'Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // quizQuestions
  {
    't6yxn8q4': {
      'en': 'Current Question:  ',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kuu74e5i': {
      'en': '  /  ',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'fi6ecy3k': {
      'en': '  correct ',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6obw0ttg': {
      'en': 'Great work!!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zapwfju3': {
      'en': 'You answered Correctly! ',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3crr8efh': {
      'en': 'Ahh no!!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6ey0k4d6': {
      'en':
          'Your answer is wrong!! Sorry, better luck next time. Try again at the end of the quiz!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zjozq0ul': {
      'en': 'Next',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'cwaej344': {
      'en': 'Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // streakIncrease
  {
    '5li3og3s': {
      'en': 'Keep it up!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kgatxg6w': {
      'en': 'Go Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'eseh7fti': {
      'en': 'Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // streakReset
  {
    'bvo9kbmd': {
      'en': 'Oh No...',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '58ev1ant': {
      'en': 'Keep Practicing To Get Your Streak Back!',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6h73fhrg': {
      'en': 'Go Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd4xey6af': {
      'en': '0',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'h1jkywrs': {
      'en': 'Home',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // editProf
  {
    '1fpkjrox': {
      'en': 'Create your Profile',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'si2t099l': {
      'en': 'Display Name',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y29t4o3v': {
      'en': 'Your Name',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'dc33tlpg': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j43k1zoa': {
      'en': 'Please select...',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2ne2g0rb': {
      'en': 'Search for an item...',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4wtvq8ha': {
      'en': 'Your email associated with this account.',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jfyquo46': {
      'en': 'Save Changes',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
  // Miscellaneous
  {
    'p11saevc': {
      'en':
          'In order to take a picture or video, this app requires permission to access the camera.',
      'am': 'ፎቶ ወይም ቪዲዮ ለማንሳት ይህ መተግበሪያ ካሜራውን ለመድረስ ፍቃድ ይፈልጋል።',
      'ar':
          'لالتقاط صورة أو مقطع فيديو، يتطلب هذا التطبيق إذنًا للوصول إلى الكاميرا.',
      'es':
          'Para tomar una foto o grabar un video, esta aplicación requiere permiso para acceder a la cámara.',
      'fr':
          'Afin de prendre une photo ou une vidéo, cette application nécessite une autorisation pour accéder à la caméra.',
      'ja': '写真やビデオを撮影するには、このアプリはカメラへのアクセス許可を必要とします。',
      'ne':
          'तस्विर वा भिडियो लिनको लागि, यो एपलाई क्यामेरा पहुँच गर्न अनुमति चाहिन्छ।',
      'ru':
          'Чтобы сделать снимок или видео, этому приложению требуется разрешение на доступ к камере.',
      'vi':
          'Để chụp ảnh hoặc quay video, ứng dụng này cần có quyền truy cập vào máy ảnh.',
      'zh_Hans': '为了拍摄照片或视频，此应用程序需要访问相机的权限。',
      'zh_Hant': '為了拍攝照片或視頻，此應用程式需要存取相機的權限。',
    },
    'glb17sde': {
      'en':
          'In order to upload data, this app requires permission to access the photo library.',
      'am': 'ውሂብ ለመስቀል ይህ መተግበሪያ የፎቶ ቤተ-መጽሐፍቱን ለመድረስ ፈቃድ ይፈልጋል።',
      'ar':
          'من أجل تحميل البيانات، يتطلب هذا التطبيق إذنًا للوصول إلى مكتبة الصور.',
      'es':
          'Para cargar datos, esta aplicación requiere permiso para acceder a la biblioteca de fotos.',
      'fr':
          'Afin de télécharger des données, cette application nécessite l\'autorisation d\'accéder à la photothèque.',
      'ja': 'データをアップロードするには、このアプリは写真ライブラリへのアクセス許可を必要とします。',
      'ne':
          'डाटा अपलोड गर्नको लागि, यो एपलाई फोटो लाइब्रेरी पहुँच गर्न अनुमति चाहिन्छ।',
      'ru':
          'Чтобы загрузить данные, этому приложению требуется разрешение на доступ к библиотеке фотографий.',
      'vi':
          'Để tải lên dữ liệu, ứng dụng này cần có quyền truy cập vào thư viện ảnh.',
      'zh_Hans': '为了上传数据，该应用程序需要访问照片库的权限。',
      'zh_Hant': '為了上傳數據，該應用程式需要存取照片庫的權限。',
    },
    '28rcui4c': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xcxp0uok': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd8i5c11m': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '7z47qewn': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'z0sjwdca': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'r7cg6gue': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'st489g7k': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '4plb7jhf': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '2f8n40gn': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'akzs59py': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'zu5eak8f': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '0rabz99e': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'jyzedmdq': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '1c0tad28': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'o1rzhm3a': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'hx7swlmy': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'n0a9pqz0': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'nrjdcq8b': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'c4rrfvfg': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '93wlvg8p': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5d8z7sgv': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'mhsok2z7': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5ignvgu1': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'azmnk88c': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '5u4svthw': {
      'en': '',
      'am': '',
      'ar': '',
      'es': '',
      'fr': '',
      'ja': '',
      'ne': '',
      'ru': '',
      'vi': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
